# Generated by `rjournal_pdf_article()` using `knitr::purl()`: do not edit by hand
# Please edit woylier_article.Rmd to modify this file

## ----setup, include=FALSE-----------------------------------------------------
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(tourr)
library(tidyverse)
library(woylier)
library(geozoo)
library(ggplot2)
library(patchwork)


## ----splines2d-static, echo = FALSE, fig.height = 5, fig.cap="The plot on the right hand side is 30 degree rotation of the left hand side. The calculated splines index is shown on top of each plots. Although they depicts the same points we can see that splines index is different which show the rotational variance of splines index.", include=knitr::is_html_output(), eval=knitr::is_html_output(), fig.alt = "Two side by side scatterplots with 6 points. The plot on the right hand side is 30 degree rotation of the left hand side. The calculated splines index is shown on top of each plots. Although they depicts the same points we can see that splines index is different which show the rotational variance of splines index. "----
#> data("sine_curve")
#> mat <- data.frame(sine_curve[,5:6])
#> mat_idx <- round(tourr::splines2d()(mat), 2)
#> mat_rot <- data.frame(x = cos(pi/6) * sine_curve$V5 +
#>                           sin(pi/6) * sine_curve$V6,
#>                       y = -sin(pi/6) * sine_curve$V5 +
#>                            cos(pi/6) * sine_curve$V6)
#> mat_rot_idx <- round(tourr::splines2d()(mat_rot), 2)
#> p1 <- ggplot(mat, aes(x=V5, y=V6)) +
#>   geom_point() +
#>   ggtitle(paste("Splines index = ", mat_idx)) +
#>   theme(aspect.ratio=1)
#> p2 <- ggplot(mat_rot, aes(x=x, y=y)) +
#>   geom_point() +
#>   xlab("Rotated 1") + ylab("Rotated 2") +
#>   ggtitle(paste("Splines index = ", mat_rot_idx)) +
#>   theme(aspect.ratio=1)
#> p1+p2


## -----------------------------------------------------------------------------
d <- sphere.hollow(p = 3, n = 1000)
#d <- sphere.hollow(p = 5, n = 1000)
d <- data.frame(d$points)
#animate_xy(d, axes="off") 
# include gif of the a sphere and torus


## ----echo = FALSE, include=FALSE----------------------------------------------
set.seed(2022)
p <- 6
base1 <- tourr::basis_random(p, d=1)
base2 <- tourr::basis_random(p, d=1)

frames <- givens_full_path(base1, base2, nsteps = 10)

sp <- generate_space_view(p=p)

sp_path <- add_path(sp, frames)

point1 <- as.data.frame(t(base1))
point1$type <- "point1"

point2 <- as.data.frame(t(base2))
point2$type <- "point2"

sp_path <- rbind(sp_path, point1, point2)

tourr::render_gif(sp_path[,1:p], 
                  tour_path = grand_tour(),
                  display = display_xy(axes="bottomleft", col=sp_path$type),
                  frames = 100,
                  "sphere.gif")


## ----1d-path-dynamic, echo = FALSE, fig.height = 3, fig.cap="Interpolation steps of 1D projections of 6D data", include=knitr::is_html_output(), eval=knitr::is_html_output(), fig.alt = "2 highlighted points on the surface of sphere connected by 10 interpolated steps, rotating."----
#> knitr::include_graphics("sphere.gif")


## ----echo = FALSE, include=FALSE----------------------------------------------
set.seed(2022)
p <- 6
n <- 1500
d <- 2
base1 <- tourr::basis_random(p, d=2)
base2 <- tourr::basis_random(p, d=2)
frames_2d <- givens_full_path(base1, base2, 10)
proj_2d <- map(1:n, ~basis_random(n = p,  d=d)) %>%
  purrr::flatten_dbl() %>% 
  matrix(ncol = p*2, byrow = TRUE) %>%
  as_tibble()
path_2d <- t(apply(frames_2d, 3, c)) %>% 
  as.data.frame()
proj_2d <- proj_2d %>% 
  mutate(type="torus")
path_2d <- path_2d %>% 
  mutate(type="path")
proj_path <- bind_rows(proj_2d, path_2d)

tourr::render_gif(proj_path[,1:6], 
                  tour_path = grand_tour(),
                  display = display_xy(axes="bottomleft", col=proj_path$type),
                  frames = 100,
                  "torus.gif")


## ----2d-path-dynamic, echo = FALSE, fig.height = 3, fig.cap="Interpolation steps of 2D projections of 6D data", include=knitr::is_html_output(), eval=knitr::is_html_output(), fig.alt = "2 highlighted points on the surface of torus connected by 10 interpolated steps, rotating."----
#> 
#> knitr::include_graphics("torus.gif")


## ---- include=FALSE-----------------------------------------------------------
library(plotly)
library(ggplot2)
library(palmerpenguins)


## ----penguins-alison, out.width = "100%", out.height = "30%", fig.cap = "Artwork by \\@allison\\_horst", fig.alt="A picture of three different penguins with their species: Chinstrap, Gentoo, and Adelie. "----
knitr::include_graphics("penguins.png")


## ----penguins-tab-interactive, eval = knitr::is_html_output(), layout = "l-body-outset"----
#> knitr::kable(head(penguins), format = "html", caption = "A basic table")


## ----penguins-tab-static, eval = knitr::is_latex_output()---------------------
knitr::kable(head(penguins), format = "latex", caption = "A basic table") %>% 
  kableExtra::kable_styling(font_size = 7)


## ----penguins-plotly, echo = TRUE, fig.height = 5, fig.cap="A basic interactive plot made with the plotly package on palmer penguin data. Three species of penguins are plotted with bill depth on the x-axis and bill length on the y-axis. When hovering on a point, a tooltip will show the exact value of the bill depth and length for that point, along with the species name.", include=knitr::is_html_output(), eval=knitr::is_html_output(), fig.alt = "A scatterplot of bill length against bill depth, both measured in millimetre. The three species are shown in different colours and loosely forms three clusters. Adelie has small bill length and large bill depth, Gentoo has small bill depth but large bill length, and Chinstrap has relatively large bill depth and bill length."----
#> p <- penguins %>%
#>   ggplot(aes(x = bill_depth_mm, y = bill_length_mm,
#>              color = species)) +
#>   geom_point()
#> ggplotly(p)


## ----penguins-ggplot, echo = TRUE, fig.height = 5, fig.cap="A basic non-interactive plot made with the ggplot2 package on palmer penguin data. Three species of penguins are plotted with bill depth on the x-axis and bill length on the y-axis. Visit the online article to access the interactive version made with the plotly package.", include=knitr::is_latex_output(), eval=knitr::is_latex_output()----
penguins %>% 
  ggplot(aes(x = bill_depth_mm, y = bill_length_mm, 
             color = species)) + 
  geom_point()

